// Generated by https://quicktype.io

export interface Evnt {
    id:               number;
    name:             string;
    description:      string;
    address:          string;
    city:             string;
    state:            string;
    ticketPrice:      number;
    type:             string;
    hostedBy:         string;
    dateTime:         string;
    availableTickets: number;
}
